var s = {
	
	"player_count" : "players in game:",
	"you" : "you",
	"hint_for" : "Hint for",
	"guess_for" : "Guess for",
	"enter_hint_here" : "Type your hint here",
	"enter_guess_here" : "Type your guess here",
	"send" : "Send",
	"hint_mode" : "Hint giving mode",
	"guess_mode" : "Guessing mode",
	"sends_guess" : "makes a guess",
	"sends_hint" : "provides the hints",
	"sends_message" : "sends a message",
	"draw_code" : "Draw a code",
	"draws_code" : "draws a secret code",
	"reveal_code" : "Reveal your code",
	"reveals_code" : "Reveals the secret code",
	"your_code_is" : "Your secret code is:",
	"player_reveals_code" : "reveals that the secret code was:",	
	"join_red" : "Join the red team",
	"switch_to_red" : "Switch to the red team",
	"join_blue" : "Join the blue team",
	"switch_to_blue" : "Switch to the blue team",
	"joins_red" : "joins the red team",
	"joins_blue" : "joins the blue team",
	"switch_after_game" : "Team change will take effect in the next game",
	"reset" : "Start a new game",
	"enter_username" : "Enter your username:",
	"enter_username_non_empty" : "Enter your username (it can't be empty):",
	"confirm_reset" : "Are you sure you want to start a new game?",
	"started_new_game" : "started a new game!",
	"secret_words" : "Your secret words",
	"left_game" : "has left the game",
	"joined_game" : "has joined the game!",
	"reroll" : "Reroll a word",
	"ask_for_reroll" : "Which word do you want to reroll (enter its number)?",
	"enter_a_number" : "Please enter a number",
	"number_must_be_between" : "Please enter a number between",
	"between_and" : "and",
	"reroll_used_by_teammate" : "A reroll was just used up by your teammate :(",
	"rerolls_from" : "rerolls the word",
	"rerolls_to" : "into",
	"reroll_failed" : "tried to reroll, but wasn't able to",
	"rerolls_gone" : "Rerolls are no longer available",
	"hint_rules" : "You can't communicate with your team until you reveal the code. \nYou need to create a hint for each of the words below, each obeying those two rules:\n 	1. Your hint can't contain any of your secret words\n 	2. Your hint has to refer to the meaning of the secret word; hints relating to individual letters, word numbers, rhymes etc are not allowed.\nUnlike in Codenames, hints *can* contain multiple words, numbers, special characters, emojis etc.",

}