var s = {
	
	"player_count" : "players in game:",
	"you" : "you",
	"hint_for" : "Hint for",
	"guess_for" : "Guess for",
	"enter_hint_here" : "Type your hint here",
	"enter_guess_here" : "Type your guess here",
	"send" : "Send",
	"hint_mode" : "Hint giving mode",
	"guess_mode" : "Guessing mode",
	"sends_guess" : "makes a guess",
	"sends_hint" : "provides the hints",
	"sends_message" : "sends a message",
	"draw_code" : "Draw a code",
	"draws_code" : "draws a secret code",
	"reveal_code" : "Reveal your code",
	"reveals_code" : "Reveals the secret code",
	"your_code_is" : "Your secret code is:",
	"player_reveals_code" : "reveals that the secret code was:",	
	"join_red" : "Join the red team",
	"join_blue" : "Join the blue team",
	"joins_red" : "joins the red team",
	"joins_blue" : "joins the blue team",
	"switch_after_game" : "Team change will take effect in the next game",
	"reset" : "Start a new game",
	"enter_username" : "Enter your username:",
	"enter_username_non_empty" : "Enter your username (it can't be empty):",
	"confirm_reset" : "Are you sure you want to start a new game?",
	"started_new_game" : "started a new game!",
	"secret_words" : "Your secret words",
	"left_game" : "has left the game",
	"joined_game" : "has joined the game!",
}