var s = {
	
	"player_count" : "players in game:",
	"you" : "you",
	"hint_for" : "Hint for",
	"guess_for" : "Guess for",
	"enter_hint_here" : "Type your hint here",
	"enter_guess_here" : "Type your guess here",
	"send" : "Send",
	"hint_mode" : "Hint giving mode",
	"guess_mode" : "Guessing mode",
	"sends_guess" : "makes a guess",
	"sends_hint" : "provides the hints",
	"sends_message" : "sends a message",
	"draw_code" : "Draw a code",
	"draws_code" : "draws a secret code",
	"reveal_code" : "Reveal your code",
	"reveals_code" : "reveals the secret code",
	"your_code_is" : "Your secret code is:",
	"player_reveals_code" : "reveals that the secret code was:",	
	"join_R" : "Join the red team",
	"switch_to_R" : "Switch to the red team",
	"join_B" : "Join the blue team",
	"switch_to_B" : "Switch to the blue team",
	"joins_R" : "joins the red team",
	"joins_B" : "joins the blue team",
	"switch_after_game" : "Team change will take effect in the next game",
	"reset" : "Start a new game",
	"enter_username" : "Enter your username:",
	"enter_username_non_empty" : "Enter your username (it can't be empty):",
	"confirm_reset" : "Are you sure you want to start a new game?",
	"started_new_game" : "started a new game!",
	"secret_words" : "Your secret words",
	"left_game" : "has left the game",
	"joined_game" : "has joined the game!",
	"reroll" : "Reroll a word",
	"ask_for_reroll" : "Which word do you want to reroll (enter its number)?",
	"enter_a_number" : "Please enter a number",
	"number_must_be_between" : "Please enter a number between",
	"between_and" : "and",
	"reroll_used_by_teammate" : "A reroll was just used up by your teammate :(",
	"rerolls_from" : "rerolls the word",
	"rerolls_to" : "into",
	"reroll_failed" : "tried to reroll, but wasn't able to",
	"rerolls_gone" : "Rerolls are no longer available",
	"hint_rules" : "You can't communicate with your team until you reveal the code. \nYou need to create a hint for each of the words below, each obeying those two rules:\n 	1. Your hint can't contain any of your secret words\n 	2. Your hint has to refer to the meaning of the secret word; hints relating to individual letters, word numbers, rhymes etc are not allowed.\nUnlike in Codenames, hints *can* contain multiple words, numbers, special characters, emojis etc.",
	"intercept_icon" : "🔑",
	"failure_icon" : "⁉",
	"not_your_turn" : "It's not your turn yet",
	"game_end_tie" : "The last round has finished! Tie breaking hasn't been implemented yet, so you'll have to do it yourself  ;)",
	"game_end_R" : "The red team has won!",
	"game_end_B" : "The blue team has won!",
	"your_time_to_guess_ally" : "It's now your team's turn to guess your code",
	"your_time_to_guess_enemy" : "It's now your team's turn to guess the enemy code",
	"enemy_time_to_guess_ally" : "The enemy team will now try to guess your code",
	"enemy_time_to_guess_enemy" : "The enemy team will now try to guess their code",
	"gains_intercept_R" : "The red team gains an intercept token",
	"gains_intercept_B" : "The blue team gains a intercept token",
	"gains_failure_R" : "The red team gains an failure token",
	"gains_failure_B" : "The blue team gains a failure token",
	"starts_R" : "The red team starts!",
	"starts_B" : "The blue team starts!",
	"already_have_code" : "You already have a code:",
	"round_start_1" : "Round",
	"round_start_2" : "begins.",
	"round" : "Round",
	"" : "",
	"" : "",
	"" : "",
	"" : "",
	"status" : "Game status",
	"status_0" : "There is no active game.",
	"status_1_R" : "Waiting for the red team to give a clue.",
	"status_1_B" : "Waiting for the blue team to give a clue.",
	"status_2_R" : "Waiting for the red team to guess the enemy code.",
	"status_2_B" : "Waiting for the blue team to guess the enemy code.",
	"status_3_R" : "Waiting for the red team to guess their own code.",
	"status_3_B" : "Waiting for the blue team to guess their own code.",
	"status_4" : "Waiting for code reveal from the hint giver.",
	"status_5" : "End of the round, waiting for some processing to finish.",

}