var plStrings = {
	"default_words" : ["pl_basic","pl_typy_pokemonów","pl_fantasy"],
	"reroll_words" : ["pl_basic"],

	"player_count": "gracze w grze:",
	"you": "ty",
	"hint_for": "Wskazówka do",
	"guess_for": "Słowo do",
	"enter_hint_here": "Tu wpisz swoją wskazówkę",
	"enter_guess_here": "Tu wpisz numer słowa",
	"send": "Wyślij",
	"hint_mode": "Tryb wskazówek",
	"guess_mode": "Tryb zgadywania",
	"sends_guess": "zgaduje",
	"sends_hint": "daje wskazówkę",
	"sends_message": "wysyła wiadomość",
	"draw_code": "Dobierz kod",
	"draws_code": "dobiera tajny kod",
	"reveals_code": "ujawnia tajny kod",
	"your_code_is": "Twój tajny kod to:",
	"player_reveals_code": "ujawnia, swój tajny kod:",
	"join_R": "Dołącz do czerwonych",
	"switch_to_R": "Przejdź do czerwonych",
	"join_B": "Dołącz do niebieskich",
	"switch_to_B": "Przejdź do niebieskich",
	"joins_R": "dołącza do czerwonych",
	"joins_B": "dołącza do niebieskich",
	"switch_after_game": "Twoja drużyna zmieni się w następnej grze",
	"reset": "Zacznij nową grę",
	"enter_username": "Podaj swoją nazwę użytkownika. Najlepiej taką samą jak na czacie głosowym.",
	"enter_username_non_empty": "Wpisz swoją nazwę użytkownika (nie może być pusta). Najlepiej taką samą jak na czacie głosowym.",
	"enter_room_name": "Wpisz nazwę pokoju aby do niego dołączyć lub stworzyć nowy.",
	"shareable_link": "Link zapraszający do tego pokoju:",
	"confirm_reset": "Czy na pewno chcesz zacząć nową grę?",
	"started_new_game": "zaczyna nową grę!",
	"secret_words": "Twoje tajne słowa",
	"left_game": "opuszcza grę",
	"left_game_with_code": "opuszcza grę, zabierając ze sobą tajny kod. Wracamy do kroku dawania podpowiedzi...",
	"joined_game": "dołącza do gry!",
	"reroll": "Wymień słowo",
	"ask_for_reroll": "Które słowo chcesz wymienić (podaj jego numer)?",
	"enter_a_number": "Wpisz liczbę",
	"number_must_be_between": "Wpisz liczbę pomiędzy",
	"between_and": "a",
	"reroll_used_by_teammate": "Wymiana została właśnie zużyta przez twoją drużynę :(",
	"rerolls_from": "wymienia słowo",
	"rerolls_to": "na",
	"reroll_failed": "nie udało się wymienić słowa.",
	"rerolls_gone": "Wymiany słów nie są już dostępne.",
	"hint_rules": "Nie możesz wspominać ani w żaden sposób sugerować jaki jest twój kod, dopóki nie zostanie ujawniony. \nMusisz stworzyć podpowiedź dla każdego z poniższych słów, przestrzegając tych dwóch zasad: \n1. Twoja podpowiedź nie może zawierać żadnego z twoich tajnych słów. \n2. Twoja podpowiedź musi odnosić się do znaczenia odpowiadającego jej tajnego słowa; podpowiedzi odnoszące się do poszczególnych liter, cyfr wyrazów, rymów itp.\nW przeciwieństwie do Tajniaków, podpowiedzi *mogą* zawierać wiele słów, liczby, znaki specjalnych, emoji itp.",
	"intercept_icon": "🔑",
	"failure_icon": "☠️",
	"code_icon" : "🧾",
	"swap_icon" : "🔀",
	"not_your_turn": "Jeszcze nie twoja kolej.",
	"game_end_tie": "Ostatnia runda się skończyła! Łamanie remisów nie zostało jeszcze zaimplementowane, więc będziecie musieli zrobić to sami ;)",
	"game_end_R": "Czerwona drużyna wygrała!",
	"game_end_B": "Niebieska drużyna wygrała!",
	"your_time_to_guess_ally": "Teraz kolej twojej drużyny aby odgadnąć swój kod.",
	"your_time_to_guess_enemy": "Teraz kolej twojej drużyny aby odgadnąć kod przeciwników.",
	"enemy_time_to_guess_ally": "Drużyna przeciwna będzie teraz próbowała odgadnąć wasz kod.",
	"enemy_time_to_guess_enemy": "Drużyna przeciwna będzie teraz próbowała odgadnąć swój kod.",
	"time_for_hint_R": "Teraz kolej na wskazówkę od czerwonej drużyny.",
	"time_for_hint_B": "Teraz kolej na wskazówkę od niebieskiej drużyny.",
	"gains_intercept_R": "Czerwona drużyna zdobywa żeton sukcesu!",
	"gains_intercept_B": "Niebieska drużyna zdobywa żeton sukcesu!",
	"gains_failure_R": "Czerwona drużyna dostaje symbol porażki!",
	"gains_failure_B": "Niebieska drużyna dostaje symbol porażki!",
	"starts_R": "Zaczyna czerwona drużyna!",
	"starts_B": "Zaczyna niebieska drużyna!",
	"already_have_code": "Już masz kod",
	"round_start_1": "Runda",
	"round_start_2": "zaczyna się.",
	"round": "Runda",
	"status": "Stan gry",
	"status_0": "Nie ma aktywnej gry.",
	"status_1_R": "Czerwona drużyna daje wskazówkę.",
	"status_1_B": "Niebieska drużyna daje wskazówkę.",
	"status_2_R": "Niebieska drużyna odgaduje kod czerownych.",
	"status_2_B": "Czerwona drużyna odgaduje kod niebieskich.",
	"status_3_R": "Czerwona drużyna odgaduje swój kod.",
	"status_3_B": "Niebieska drużyna odgaduje swój kod.",
	"status_4": "Oczekiwanie na ujawnienie tajnego kodu.",
	"status_5": "Przetwarzanie końca rundy.",
	"confirm_hint_override": "W grze jest już aktywna podpowiedź. Jeśli dasz kolejną teraz, to poprzednia zostanie nadpisana. Czy na pewno chcesz to zrobić?\n Użyj tej opjci tylko wtedy, gdy dający podpowiedź opóści grę.",
	"no_team": "Nie należysz jeszcze do żadnej drużyny.",
	"current_hint": "Aktualna wskazówka to",
	"change_lang" : "Zmień język",
	"reveal_words" : "Ujawnij tajne słowa",
	"reveals_words" : "Ujawnia swoje tajne słowa",
	"code_was" : "Tajnym kodem było",

}